#!/bin/bash
# Script para cadastrar 50 produtos de exemplo no WooCommerce via WP-CLI

WP_ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
WP="php $WP_ROOT/wp-cli.phar --path=$WP_ROOT"

# Produtos de exemplo (nome|preço|categoria|descrição)
PRODUTOS=(
  "Resistor 1kΩ 1/4W|0.25|Resistores|Resistor de 1kΩ, potência 1/4W. Ideal para projetos eletrônicos."
  "Resistor 10kΩ 1/4W|0.25|Resistores|Resistor de 10kΩ, potência 1/4W. Ideal para projetos eletrônicos."
  "Resistor 220Ω 1/4W|0.25|Resistores|Resistor de 220Ω, potência 1/4W. Ideal para projetos eletrônicos."
  "Resistor 4.7kΩ 1/4W|0.25|Resistores|Resistor de 4.7kΩ, potência 1/4W. Ideal para projetos eletrônicos."
  "Capacitor Cerâmico 100nF|0.30|Capacitores|Capacitor cerâmico de 100nF para desacoplamento."
  "Capacitor Cerâmico 10nF|0.30|Capacitores|Capacitor cerâmico de 10nF para desacoplamento."
  "Capacitor Eletrolítico 10uF 25V|0.50|Capacitores|Capacitor eletrolítico de 10uF, 25V."
  "Capacitor Eletrolítico 1uF 50V|0.50|Capacitores|Capacitor eletrolítico de 1uF, 50V."
  "Transistor BC547 NPN|0.40|Transistores|Transistor NPN BC547 para uso geral."
  "Transistor BC557 PNP|0.40|Transistores|Transistor PNP BC557 para uso geral."
  "Transistor 2N2222 NPN|0.45|Transistores|Transistor NPN 2N2222 para uso geral."
  "Transistor IRF540 MOSFET|2.00|Transistores|Transistor MOSFET IRF540 para aplicações de potência."
  "Diodo 1N4007|0.20|Diodos|Diodo retificador 1N4007."
  "Diodo Zener 5.1V|0.30|Diodos|Diodo zener para proteção de circuitos."
  "Diodo LED 5mm Vermelho|0.15|Diodos|LED vermelho 5mm para sinalização."
  "Diodo LED 5mm Verde|0.15|Diodos|LED verde 5mm para sinalização."
  "CI 555 Timer|2.50|Circuitos Integrados|Circuito integrado 555 para temporização."
  "CI 4017 Decodificador|3.00|Circuitos Integrados|CI 4017 para contadores e decodificadores."
  "CI 4093 NAND|2.80|Circuitos Integrados|Circuito integrado 4093 NAND."
  "CI 4011 NAND|2.80|Circuitos Integrados|Circuito integrado 4011 NAND."
  "Conector Borne 2 Vias|1.20|Conectores|Conector borne de 2 vias para placas de circuito."
  "Conector P4 Macho|0.80|Conectores|Conector P4 macho para alimentação."
  "Sensor de Temperatura LM35|4.50|Sensores|Sensor de temperatura LM35 para medições precisas."
  "Sensor de Luz LDR|1.00|Sensores|Sensor LDR para detecção de luminosidade."
  "Sensor de Movimento PIR|7.00|Sensores|Sensor PIR para detecção de movimento."
  "Sensor de Umidade do Solo|5.00|Sensores|Sensor para medir umidade do solo."
  "Ferro de Solda 40W|25.00|Ferramentas|Ferro de solda 40W para montagem de placas."
  "Sugador de Solda|8.00|Ferramentas|Sugador de solda para retrabalho."
  "Multímetro Digital|35.00|Ferramentas|Multímetro digital para medições elétricas."
  "Protoboard 830 pontos|18.00|Ferramentas|Protoboard de 830 pontos para montagem de circuitos."
  "Fita Isolante 18mm|2.50|Ferramentas|Fita isolante 18mm para isolamento elétrico."
  "Chave Philips Pequena|3.00|Ferramentas|Chave Philips pequena para eletrônica."
  "Chave de Fenda Pequena|3.00|Ferramentas|Chave de fenda pequena para eletrônica."
  "Alicate de Corte|12.00|Ferramentas|Alicate de corte para eletrônica."
  "Alicate de Bico|12.00|Ferramentas|Alicate de bico para eletrônica."
  "Fonte de Alimentação 12V|45.00|Ferramentas|Fonte de alimentação 12V para bancadas."
  "Display LCD 16x2|15.00|Circuitos Integrados|Display LCD 16x2 para projetos."
  "Display 7 segmentos|2.00|Circuitos Integrados|Display de 7 segmentos para projetos."
  "Potenciômetro 10k|1.20|Resistores|Potenciômetro de 10k para ajuste de sinais."
  "Trimpot 10k|1.00|Resistores|Trimpot de 10k para ajuste fino."
  "Buzzer Piezoelétrico|1.50|Circuitos Integrados|Buzzer piezoelétrico para sinalização."
  "Relé 5V|3.00|Circuitos Integrados|Relé 5V para acionamento de cargas."
  "Relé 12V|3.00|Circuitos Integrados|Relé 12V para acionamento de cargas."
  "Cristal Oscilador 16MHz|1.00|Circuitos Integrados|Cristal oscilador de 16MHz."
  "Cristal Oscilador 4MHz|1.00|Circuitos Integrados|Cristal oscilador de 4MHz."
  "Barra de Pinos 40 vias|1.20|Conectores|Barra de pinos 40 vias para prototipagem."
  "Jumpers Macho-Macho|2.00|Conectores|Kit de jumpers macho-macho para protoboard."
  "Jumpers Macho-Fêmea|2.00|Conectores|Kit de jumpers macho-fêmea para protoboard."
  "Jumpers Fêmea-Fêmea|2.00|Conectores|Kit de jumpers fêmea-fêmea para protoboard."
  "Placa Universal 5x7cm|2.50|Ferramentas|Placa universal para montagem de circuitos."
  "Placa Universal 7x9cm|3.00|Ferramentas|Placa universal para montagem de circuitos."
)

for PROD in "${PRODUTOS[@]}"
do
  NOME="$(echo $PROD | cut -d'|' -f1)"
  PRECO="$(echo $PROD | cut -d'|' -f2)"
  CATEGORIA="$(echo $PROD | cut -d'|' -f3)"
  DESC="$(echo $PROD | cut -d'|' -f4)"
  $WP post create --post_type=product --post_title="$NOME" --post_status=publish --meta_input="{\"_price\":\"$PRECO\",\"_stock_status\":\"instock\"}" --tax_input="{\"product_cat\":[\"$CATEGORIA\"]}" --post_content="$DESC"
done

echo "Cadastro de produtos concluído."
